### ISSUE TITLE
`flowcarre()` does not accept (character) vectors

### ISSUE THREAD

**Issue by Bakaniko** [fbahoken/cartogRaflow#1]
When trying to execute `flowcarre()` with a character vector instead of a dataframe, the following error appears :
```
Error in matrix(data = c(0), nrow = nbi, ncol = nbi, dimnames = list(c(as.matrix(liste)),  : 
  non-numeric matrix extent
```
# Possible issue
I think the problem is at line [41](https://github.com/fbahoken/cartogRaflow/blob/master/R/flowcarre.R#L41) where `nbi` is calculated.

```r
flowcarre<-function(liste, tab, origin, dest,valflow,empty.sq,format,diagonale){
    str(liste)
    nbi<-dim(liste)[1]
    matrice<-matrix(data = c(0),nrow = nbi,ncol = nbi,
        dimnames = list(c(as.matrix(liste)), c(as.matrix(liste))))
```

# How to reproduce :
```r
liste <- c("toto", "titi", "tata")
flowcarre(liste, format = "L") # returns the error

## Reason :
dim(liste)[1] # returns NULL so the matrice can't be created
```

# Possible fix
- check the entry format and apply dimension calculation accordingly (`length()` for vectors)
- Create a try/catch to test is dim(liste)[1] > 0 and throws an error if not

**Comment by fbahoken** [comment]
This error is normal because you did not declare all the require parameters.
You have to enter a (1) a vector 'liste' of ID geographic codes, which can be numeric or not and (2) a "tab" file which corresponds to the matrix you want the reduction.
See also the 'flowcarre' function examples.
